# File: .github/workflows/ADDS-Single-Site.yml
on: [push]
name: ADDS-Single-Site
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TimeZone: "GMT Standard Time"
      Location: "uksouth"
      namingConvention: "adl"
      VNet1ID: "10.0"
      DeploymentDir: "ADDS-Single-Site"
      AutoShutdownEnabled: "Yes"
      AutoShutdownTime: "2000"
      AutoShutdownEmail: "someone@domain.com"
      adminUsername: ${{ secrets.ADMIN_USERNAME }}
      adminPassword: ${{ secrets.ADMIN_PASSWORD }}
      WindowsServerLicenseType: "Windows_Server"
      vmDC1OSVersion: "2022-Datacenter-azure-edition-core-smalldisk"
      vmDC1VMSize: "Standard_D2s_v3"
      NetBiosDomain: "E2D"
      InternalDomainName: "adds.e2d.co.uk"
      artifactsLocation: "https://raw.githubusercontent.com/jonsmith79/AzureDevLab/main/Deployments"
      artifactsLocationSasToken: ""

    steps:
      # Checkout code
    - name: Checkout
      uses: actions/checkout@main

      # Log into Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create resource group with Azure CLI
    #- name: Azure CLI script
    #  uses: azure/CLI@v1
    #  with:
    #    scope: subscription
    #    azcliversion: 2.44.1
    #    inlineScript: az group create --name "${{env.namingConvention}}-RG2" --location ${{env.Location}}

      # Deploy Bicep file
    - name: ADDS Single Site - Azure ARM Deployment
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_ADL_SUBID }}
        region: ${{env.Location}}
        template: ./Deployments/${{env.DeploymentDir}}/deploy_ADDS-Single-Site.bicep
        parameters:
          Location="${{env.Location}}"
          namingConvention="${{env.namingConvention}}"
          VNet1ID="${{env.VNet1ID}}"
          TimeZone="${{env.TimeZone}}"
          AutoShutdownEnabled="${{env.AutoShutdownEnabled}}"
          AutoShutdownTime="${{env.AutoShutdownTime}}"
          AutoShutdownEmail="${{env.AutoShutdownEmail}}"
          adminUsername="${{env.adminUsername}}"
          adminPassword="${{env.adminPassword}}"
          WindowsServerLicenseType="${{env.WindowsServerLicenseType}}"
          vmDC1OSVersion="${{env.vmDC1OSVersion}}"
          vmDC1VMSize="${{env.vmDC1VMSize}}"
          NetBiosDomain="${{env.NetBiosDomain}}"
          InternalDomainName="${{env.InternalDomainName}}"
          artifactsLocation="${{env.artifactsLocation}}/${{env.DeploymentDir}}/"
          artifactsLocationSasToken="${{env.artifactsLocationSasToken}}"