# File: .github/workflows/ADDS-Single-Site.yml
env:
  TimeZone: "GMT Standard Time"
  Location: "uksouth"
  namingConvention: "adl"
  VNet1ID: "10.0"
  DeploymentName: "ADDS-Single-Site"
  ResourceGroup: "adl-RG"
  


on: [push]

name: ADDS-Single-Site

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: ADDS-Single-Site_Azure-ARM-Deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_ADL_SUBID }}
        resourceGroupName: ${{ env.ResourceGroup }}
        template: Deployments/${{env.DeploymentName}}/azuredeploy.bicep
        parameters:
          Location="${{env.Location}}"
          namingConvention="${{env.namingConvention}}"
          VNet1ID="${{env.VNet1ID}}"
