# File: .github/workflows/ADDS-Single-Site.yml
on: [push]
name: ADDS-Single-Site
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TimeZone: "GMT Standard Time"
      Location: "uksouth"
      namingConvention: "adl"
      VNet1ID: "10.0"
      DeploymentName: "ADDS-Single-Site"
      ResourceGroupName: "${{env.namingConvention}}-RG2-DELETE-ME"

    steps:
      # Checkout code
    - name: Checkout
      uses: actions/checkout@main

      # Log into Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create resource group with Azure CLI
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.44.1
        inlineScript: az group create --name ${{env.ResourceGroupName}} --location ${{env.Location}}

      # Deploy Bicep file
    - name: ADDS Single Site - Azure ARM Deployment
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_ADL_SUBID }}
        region: ${{env.Location}}
        template: ./Deployments/${{env.DeploymentName}}/azuredeploy.bicep
        parameters:
          Location="${{env.Location}}"
          namingConvention="${{env.namingConvention}}"
          VNet1ID="${{env.VNet1ID}}"