# File: .github/workflows/Intune.yml
on: 
  push:
    branches: [ main ]

name: IntuneConfiguration

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      #location: "uksouth"
      #DeploymentDir: "Intune"
      #adminUsername: ${{ secrets.ADMIN_USERNAME }}
      #adminPassword: ${{ secrets.ADMIN_PASSWORD }}
      #artifactsLocation: "https://raw.githubusercontent.com/jonsmith79/AzureDevLab/main/Deployments"
      #artifactsLocationSasToken: ""
      azGroupPrefix: "SG"
      azBreakGlassGroupName: "CA-BreakGlass"
      azBreakGlassGroupDescription: "Break Glass Group for Azure Conditional Access Policies"
      azBreakGlassAccountDisplayName: "Break Glass"
      azBreakGlassAccountUPN: "Break.Glass@e2d.co.uk"
      azBreakGlassAccountPwd: ${{ secrets.ADMIN_PASSWORD }}
      azGARoleDefinitionId: "62e90394-69f5-4237-9190-012177145e10"

    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@main

    # Log into Azure
    - name: 'Az CLI Login'
      uses: azure/login@v1
      with:
        client-id: ${{secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{secrets.AZURE_TENANT_ID}}
        #subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        allow-no-subscriptions: true

    
    # Create Azure AD Break Glass Group with Azure CLI
    # - name: Create Azure Break Glass Group
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.44.1
    #     inlineScript: az ad group create --display-name "${{env.azBreakGlassGroupName}}" --mail-nickname "${{env.azBreakGlassGroupName}}" --description "${{env.azBreakGlassGroupDescription}}"

    # Create Azure AD Break Glass Group with Azure CLI
    - name: 'Create Azure AD Break Glass Group'
      run: |
        azBGGroupExists=$(az ad group list --display-name "${{env.azGroupPrefix}}-${{env.azBreakGlassGroupName}}" --query "[].id" --output tsv)
        if [ -z "$azBGGroupExists" ]; then
          az ad group create --display-name "${{env.azGroupPrefix}}-${{env.azBreakGlassGroupName}}" --mail-nickname "${{env.azGroupPrefix}}-${{env.azBreakGlassGroupName}}" --description "${{env.azBreakGlassGroupDescription}}"
        else
          echo "Group already exists"
        fi

    # Create Azure AD Break Glass Account with Azure CLI
    - name: 'Create Azure AD Break Glass Account'
      run: |
        azBGUserExists=$(az ad user list --upn "${{env.azBreakGlassAccountUPN}}" --query "[].id" --output tsv)
        if [ -z "$azBGUserExists" ]; then
          az ad user create --display-name "${{env.azBreakGlassAccountDisplayName}}" --password "${{env.azBreakGlassAccountPwd}}" --user-principal-name "${{env.azBreakGlassAccountUPN}}" --force-change-password-next-sign-in false
        else
          echo "User already exists"
        fi

    # Add Break Glass Account to Break Glass Group with Azure CLI
    - name: 'Add Break Glass Account to Break Glass Group'
      run: |
        azBGGroupId=$(az ad group list --display-name "${{env.azGroupPrefix}}-${{env.azBreakGlassGroupName}}" --query "[].id" --output tsv)
        azBGUserId=$(az ad user list --upn "${{env.azBreakGlassAccountUPN}}" --query "[].id" --output tsv)
        azBGAlreadyMember=$(az ad group member check --group ${azBGGroupId} --member-id ${azBGUserId} --query "value" --output tsv)
        if [ "$azBGAlreadyMember" = "false" ]; then
          az ad group member add --group ${azBGGroupId} --member-id ${azBGUserId}
        else
          echo "User already a member of the group"
        fi

    # Add Break Glass Account to Azure AD Built-in role 'Global Admin' role with Azure CLI
    - name: 'Add Break Glass Account to Azure AD Built-in role Global Admin role'
      run: |
        azBGUserId=$(az ad user list --upn "${{env.azBreakGlassAccountUPN}}" --query "[].objectId" --output tsv)
        echo ${azBGUserId}
        URI=$(echo "https://graph.microsoft.com/beta/directoryRoles")
        user_role=$("Global Administrator")
        roleDefinitionId=$(az rest --method GET --uri $URI --header Content-Type=application/json | jq --arg displayName "$user_role" '.value[] | select(.displayName | contains($displayName))' | jq '.id' -r)
        BODY=$( jq -n \
          --arg principalId "$azBGUserId" \
          --arg roleDefinitionId "$roleDefinitionId" \
          --arg directoryScopeId "/" \
          '{principalId: $principalId, roleDefinitionId: $roleDefinitionId, directoryScopeId: $directoryScopeId}'
        )
        echo $BODY
        uriRoleAssignment=$(echo "https://graph.microsoft.com/beta/roleManagement/directory/roleAssignments")
        az rest --method POST --uri $uriRoleAssignment --body "$BODY" --header Content-Type=application/json
        
        

        

        

    

    # # Deploy Bicep file
    # - name: Intune - GitHub Action Deployment
    #   uses: azure/arm-deploy@v1
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_ADL_SUBID }}
    #     region: ${{env.location}}
    #     template: ./Deployments/${{env.DeploymentDir}}/deployIntune.bicep
    #     parameters:
    #       adminUsername="${{env.adminUsername}}"
    #       adminPassword="${{env.adminPassword}}"
    #       artifactsLocation="${{env.artifactsLocation}}/${{env.DeploymentDir}}/"
    #       artifactsLocationSasToken="${{env.artifactsLocationSasToken}}"
    #       azGroupPrefix="${{env.azGroupPrefix}}"
    #       azBreakGlassGroupName="${{env.azBreakGlassGroupName}}"

    # Az logout and security hardening
    - name: 'Az logout and security hardening'
      run: |
        az logout
        az cache purge
        az account clear  