# File: .github/workflows/Intune.yml
on: 
  push:
    branches: [ main ]

name: IntuneConfiguration

permissions:
  id-token: write
  contents: read

jobs:
  Windows-latest:
    runs-on: windows-latest
    env:
      location: "uksouth"
      DeploymentDir: "Intune"
      adminUsername: ${{ secrets.ADMIN_USERNAME }}
      adminPassword: ${{ secrets.ADMIN_PASSWORD }}
      artifactsLocation: "https://raw.githubusercontent.com/jonsmith79/AzureDevLab/main/Deployments"
      artifactsLocationSasToken: ""
      azGroupPrefix: "SG"
      azBreakGlassGroupName: "SG-CA-BreakGlass"
      azBreakGlassGroupDescription: "Break Glass Group for Azure Conditional Access Policies"

    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@main

    # Log into Azure
    - name: OIDC Login to Azure Public Cloud
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    
    # Create Azure AD Break Glass Group with Azure CLI
    - name: Create Azure Break Glass Group
      uses: azure/CLI@v1
      with:
        azcliversion: 2.44.1
        inlineScript: az ad group create --display-name "${{env.azBreakGlassGroupName}}" --mail-nickname "${{env.azBreakGlassGroupName}}" --description "${{env.azBreakGlassGroupDescription}}"



   
    # Create resource group with Azure CLI
    #- name: Azure CLI script
    #  uses: azure/CLI@v1
    #  with:
    #    azcliversion: 2.44.1
    #    inlineScript: az group create --name "${{env.namingConvention}}-RG2" --location ${{env.Location}}

    # # Deploy Bicep file
    # - name: Intune - GitHub Action Deployment
    #   uses: azure/arm-deploy@v1
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ secrets.AZURE_ADL_SUBID }}
    #     region: ${{env.location}}
    #     template: ./Deployments/${{env.DeploymentDir}}/deployIntune.bicep
    #     parameters:
    #       adminUsername="${{env.adminUsername}}"
    #       adminPassword="${{env.adminPassword}}"
    #       artifactsLocation="${{env.artifactsLocation}}/${{env.DeploymentDir}}/"
    #       artifactsLocationSasToken="${{env.artifactsLocationSasToken}}"
    #       azGroupPrefix="${{env.azGroupPrefix}}"
    #       azBreakGlassGroupName="${{env.azBreakGlassGroupName}}"

    # Az logout and security hardening
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear  