# File: .github/workflows/Testing.yml
on: [push]
name: Testing
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      Location: "uksouth"
      namingConvention: "tst"
      VNet1ID: "10.1"
      DeploymentName: "Testing"

    steps:
      # Checkout code
    - name: Checkout
      uses: actions/checkout@main

      # Log into Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create resource group with Azure CLI
    #- name: Azure CLI script
    #  uses: azure/CLI@v1
    #  with:
    #    scope: subscription
    #    azcliversion: 2.44.1
    #    inlineScript: az group create --name "${{env.namingConvention}}-RG2" --location ${{env.Location}}

      # Deploy Bicep file
    - name: Testing Azure Bicep Deployment
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_ADL_SUBID }}
        region: ${{env.Location}}
        template: ./Deployments/${{env.DeploymentName}}/main.bicep
        parameters:
          location="${{env.Location}}"
          namingConvention="${{env.namingConvention}}"
          VNet1ID="${{env.VNet1ID}}"
