# File: .github/workflows/Intune.yml
on: 
    push:
      branches: [ main ]
  
name: TestIntuneConfig
  
permissions:
    id-token: write # This is required for requesting the OIDC token (JWT) from Azure AD
    contents: read # This is required for actions/checkout
  
jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    env:
      azEcho1: "Echoing from current job"
      testArray: "1,2,3,4,5"
      testArray2: |
        "SG-Intune-Test-Group-1"
        "SG-Intune-Test-Group-2"
        "SG-Intune-Test-Group-3"
        "SG-Intune-Test-Group-4"
        "SG-Intune-Test-Group-5"
      testArray3: '[{"name":"Test-Group1","description":"Test Group 1 from a GitHub Actions array"},{"name":"Test-Group2","description":"Test Group 2 from a GitHub Actions array"},{"name":"Test-Group3","description":"Test Group 3 from a GitHub Actions array"},{"name":"Test-Group4","description":"Test Group 4 from a GitHub Actions array"},{"name":"Test-Group5","description":"Test Group 5 from a GitHub Actions array"}]'
      
    steps:
      # Do something
      - name: Checkout
        uses: actions/checkout@main

      # Log into Azure
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          #subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          allow-no-subscriptions: true

      # Echo from current job
      - name: 'Echo azEcho1 from current job'
        run: |
          echo ${{ env.azEcho1 }}

      # Echo from testArray
      - name: 'Echo testArray from current job'
        run: |
          echo ${{ env.testArray }}

      # Echo from testArray2
      - name: 'Echo testArray2 from current job'
        run: echo "${{ env.testArray2 }}"

      # Echo from testArray3
      - name: 'Echo testArray3 from current job'
        run: |
          for group in ${{ fromJSON(env.testArray3) }}; do
            echo "Name: $group.name"
            echo "Description: $group.description"
          done



      # Logout of Azure session
      - name: Azure CLI Logout
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az cache purge
            az account clear
