# File: .github/workflows/Intune.yml
on: 
    push:
      branches: [ main ]
  
name: TestIntuneConfiguration
  
permissions:
    id-token: write
    contents: read
  
jobs:
  prereqs:
    name: Prereqs
    runs-on: ubuntu-latest
    env:
      azGroups: |
        - "SG-Intune-Test-Group1"
        - "SG-Intune-Test-Group2"
        - "SG-Intune-Test-Group3"

  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    needs: prereqs
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@main

      # Log into Azure
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          #subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          allow-no-subscriptions: true

      # Create Resource Group
      - name: 'Create Resource Group'
        each: group in $prereqs.env.azGroups
        run: |
          echo $group
