# File: .github/workflows/Intune.yml
on: 
    push:
      branches: [ main ]
  
name: TestIntuneConfig
  
permissions:
    id-token: write # This is required for requesting the OIDC token (JWT) from Azure AD
    contents: read # This is required for actions/checkout
  
jobs:
  prereqs:
    name: Prereqs
    runs-on: ubuntu-latest
    env:
      azGroups: |
        - "SG-Intune-Test-Group1"
        - "SG-Intune-Test-Group2"
        - "SG-Intune-Test-Group3"
      azEcho: "Echoing from env"

    steps:
      # Do something
      - name: Checkout
        uses: actions/checkout@main

      # Log into Azure
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          #subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          allow-no-subscriptions: true

  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    needs: prereqs
    steps:
      # Echo from prereqs
      - name: 'Echo azGroups variable'
        #each: group in $prereqs.env.azGroups
        run: |
          echo $azGroups

      # Echo from prereqs
      - name: 'Echo azEcho variable'
        run: |
          echo 'Hello world! $azEcho'




      # Logout of Azure session
      - name: Azure CLI Logout
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az cache purge
            az account clear
